github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

helpers:
  "bin/helper": "github.com/paketo-buildpacks/libjvm/cmd/helper"

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/microsoft-openjdk"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:            JDK 8
  id:              jdk
  version_pattern: "8\\.[\\d]+\\.[\\d]+"
  cpe_pattern:     "update[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jdk
    version:        "[8,9)"
- name:            JDK 11
  id:              jdk
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/foojay-dependency:main
  with:
    distro:  microsoft
    type:    jdk
    version: "11"
- name:            JDK 17
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/foojay-dependency:main
  with:
    distro:  microsoft
    type:    jdk
    version: "17"
- name:            JDK 21
  id:              jdk
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/foojay-dependency:main
  with:
    distro:  microsoft
    type:    jdk
    version: "21"

# ARM64
- name:            JDK 8 ARM64
  id:              jdk
  version_pattern: "8\\.[\\d]+\\.[\\d]+"
  cpe_pattern:     "update[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jdk
    version:        "[8,9)"
    arch:    "arm64"
- name:            JDK 11 ARM64
  id:              jdk
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/foojay-dependency:main
  with:
    distro:  microsoft
    type:    jdk
    version: "11"
    arch:    "arm64"
- name:            JDK 17 ARM64
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/foojay-dependency:main
  with:
    distro:  microsoft
    type:    jdk
    version: "17"
    arch:    "arm64"
- name:            JDK 21 ARM64
  id:              jdk
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/foojay-dependency:main
  with:
    distro:  microsoft
    type:    jdk
    version: "21"
    arch:    "arm64"
